services:
  - couchdb
branches:
  except:
    - develop
language: node_js
before_script:
  - couchdb -V | grep 1.6.1
  - ./sbin/timeout.sh
script: npm run cover
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
after_success:
  - npm run coveralls
